# -- mode: ruby --
# vi: set ft=ruby :


# Параметры виртуальной машины
VM_NAME = "ubuntu-18.04"
VM_MEMORY = 2048
VM_CPUS = 3


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"


  # Настройки виртуальной машины
  config.vm.define VM_NAME do |machine|
    machine.vm.hostname = VM_NAME
    machine.vm.network "private_network", ip: "192.168.33.10"


    machine.vm.provider "virtualbox" do |vb|
      vb.name = VM_NAME
      vb.memory = VM_MEMORY
      vb.cpus = VM_CPUS
    end


    machine.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip
      pip3 install psycopg2 django
    SHELL


    machine.vm.provision "file", source: "D:/sf/6", destination: "/vagrant/file"


    machine.vm.synced_folder ".", "/vagrant", disabled: true
  end
end